import argparse
from fvcore.common.config import CfgNode as _CfgNode


def convert_to_dict(cfg_node, key_list=[]):
    """Convert a config node to dictionary."""
    _VALID_TYPES = {tuple, list, str, int, float, bool}
    if not isinstance(cfg_node, _CfgNode):
        if type(cfg_node) not in _VALID_TYPES:
            print(
                'Key {} with value {} is not a valid type; valid types: {}'.format(
                    '.'.join(key_list), type(cfg_node), _VALID_TYPES
                ),
            )
        return cfg_node
    else:
        cfg_dict = dict(cfg_node)
        for k, v in cfg_dict.items():
            cfg_dict[k] = convert_to_dict(v, key_list + [k])
        return cfg_dict


class CfgNode(_CfgNode):
    """Remove once https://github.com/rbgirshick/yacs/issues/19 is merged."""

    def convert_to_dict(self):
        return convert_to_dict(self)


CN = CfgNode

_C = CN()
_C.LOG_DIR = 'tensorboard_logs'
_C.TAG = 'default'

_C.GPUS = [0]  # which gpus to use
_C.PRECISION = 32  # 16bit or 32bit
_C.BATCHSIZE = 3
_C.EPOCHS = 20

_C.N_WORKERS = 5
_C.VIS_INTERVAL = 5000
_C.LOGGING_INTERVAL = 500
_C.NAN_DEBUG = False
_C.NAN_DEBUG_RAISE = True

# === 新增 for VLM 規劃器 ===
_C.SEG2D_ROOT = "/path/to/segformer_b2_logits"
_C.CLIP_MODEL = "ViT-B-32"
_C.CLIP_INPUT_SIZE = 224
_C.FAST_HIDDEN_DIM = 512
_C.FAST_DECODER_LAYERS = 4
_C.FAST_DECODER_HEADS = 8
_C.FAST_RESIDUAL_SCALE = 30.0
_C.FAST_DELTA_SCALE = 4.0
_C.FAST_RESIDUAL_GATE_INIT = 0.05
_C.FAST_RESIDUAL_GATE_MIN = 0.0
_C.FAST_RESIDUAL_GATE_WARMUP_FLOOR_START = 0.0
_C.FAST_RESIDUAL_GATE_WARMUP_FLOOR_END = 0.0
_C.FAST_RESIDUAL_GATE_WARMUP_EPOCHS = 0.0
_C.FAST_DISABLE_RESIDUAL_GATE = False
_C.RESIDUAL_CONTEXT_DROP_EGO = True
_C.RESIDUAL_GATE_FREE_EPOCHS = 0.0
_C.FAST_DROPOUT = 0.0
_C.ADMLP_LR = 4e-6
_C.ADMLP_WEIGHT_DECAY = 1e-2
_C.ADMLP_FEATURE_SOURCE = "generated"
_C.ADMLP_OFFICIAL_PKL = "AD-MLP/pytorch/admlp/stp3_val/data_nuscene.pkl"
_C.ADMLP_FEATURE_MODE = "past4_command"
_C.ADMLP_PAST_FRAMES = 4
_C.ADMLP_HIDDEN_DIM = 512
_C.ADMLP_TRAJ_EMA = False
_C.ADMLP_CAN_EMA = False
_C.ADMLP_VEL_EMA = False
_C.ADMLP_ACC_EMA = False
_C.ADMLP_EMA_ALPHA = 0.2
_C.ADMLP_EMA_WINDOW = 12
_C.ADMLP_YAW_ACC_CLIP = 0.0
_C.ADMLP_ZERO_ACC = False
_C.ADMLP_ZERO_YAW_ACC = False
_C.ADMLP_CACHE_ROOT = "datas/re_thinking"
_C.LOSS_L2_W = 8.0
_C.LOSS_FDE_W = 2.0
_C.LOSS_VEL_W = 0.3
_C.LOSS_BOX_COL_W = 5.0
_C.LOSS_COL_W = 0.0
_C.LOSS_SMO_W = 0.0
_C.LOSS_DIR_W = 0.0
_C.LOSS_ENDPOINT_AUX_W = 2.0
_C.LOSS_COARSE_W = 0.0
_C.LOSS_RESIDUAL_AUX_W = 1.0
_C.LOSS_EASY_RESIDUAL_REG_W = 0.05
_C.RESIDUAL_AUX_ON_RAW = True
_C.RESIDUAL_AUX_THRESH = 0.5
_C.RESIDUAL_AUX_SOFT_SCALE = 1.0
_C.RESIDUAL_AUX_BETA = 0.5
_C.EASY_L2_WEIGHT = 1.0
_C.COARSE_COLLISION_HARD_SCALE = 1.0
_C.COARSE_COLLISION_HARD_THRESH = 0.05
_C.COARSE_COLLISION_BOX_REWEIGHT_W = 0.0
_C.LOSS_BOX_COL_IMPROVE_W = 0.0
_C.BOX_COL_IMPROVE_MARGIN = 0.0
_C.LOSS_GATE_TARGET_W = 0.0
_C.GATE_TARGET_THRESH = 0.3
_C.GATE_TARGET_SCALE = 1.0
_C.HARD_L2_REWEIGHT_W = 0.0
_C.LOSS_BEV_OBSTACLE_W = 0.3
_C.LOSS_BEV_DRIVABLE_W = 0.0
_C.LOSS_TEACHER_SCENE_W = 0.0
_C.LOSS_BEV_TEACHER_W = 0.1
_C.LOSS_TEACHER_RISK_W = 0.0
_C.LOSS_TEACHER_RISK_BCE_W = 1.0
_C.LOSS_TEACHER_RISK_MSE_W = 0.5
_C.PSEUDO_BEV_GRID_SIZE = 1.0
_C.PSEUDO_BEV_TOKEN_SIZE = 40
_C.PSEUDO_BEV_CHANNELS = 128
_C.PSEUDO_BEV_DEPTH_MIN = 1.0
_C.PSEUDO_BEV_DEPTH_MAX = 80.0
_C.PSEUDO_BEV_REL_DEPTH_SCALE = 50.0
_C.PSEUDO_BEV_VISIBLE_SIZE = 112
_C.BEVFORMER_TEACHER_BEV_ROOT = ""
_C.VAD_TEACHER_BEV_ROOT = ""
_C.BEVFORMER_TEACHER_DIM = 256
_C.BEVFORMER_TEACHER_SIZE = 50
_C.BEV_TEACHER_GATE_ENABLED = True
_C.BEV_TEACHER_GATE_INIT_BIAS = 0.0
_C.BEV_TEACHER_GATE_MIN = 0.1
_C.BEV_TOKEN_FUSION_ENABLED = False
_C.BEV_CONTEXT_FUSION_ENABLED = False
_C.BEV_EGO_RISK_CONTEXT_ENABLED = False
_C.BEV_CONTEXT_SCALE = 0.1
_C.BEV_EGO_CONTEXT_SCALE = 0.01
_C.BEV_RESIDUAL_SCALE = 0.5
_C.BEV_TEACHER_ONLY = False
_C.FREEZE_ALL_BEV = False
_C.HARD_DECODER_WARMUP_EPOCHS = 1
_C.BEV_FREEZE_WARMUP_EPOCHS = 1
_C.KEEP_PERCEPTION_FROZEN_AFTER_WARMUP = False
_C.BEV_LR_MULT = 0.1
_C.VAD_TEACHER_RISK_ROOT = ""
_C.VAD_TEACHER_RISK_SIZE = 100
_C.VAD_TEACHER_RISK_USE_VISIBLE = True
_C.VAD_TEACHER_RISK_VISIBLE_DILATE = 1
_C.VAD_TEACHER_RISK_X_MIN = 0.0
_C.VAD_TEACHER_RISK_X_MAX = 35.0
_C.VAD_TEACHER_RISK_Y_ABS = 6.0
_C.LOSS_VAD_BEV_OBSTACLE_W = 0.1
_C.LOSS_VAD_RISK_PLAN_W = 0.3
_C.VAD_RISK_PLAN_ENABLED = True
_C.VAD_VECTOR_CONTEXT_ENABLED = False
_C.VAD_VECTOR_CONTEXT_SCALE = 0.005
_C.VAD_VECTOR_CONTEXT_WARMUP_EPOCHS = 0.0
_C.VAD_VECTOR_CONTEXT_RAMP_EPOCHS = 1.0
_C.VAD_VECTOR_DETACH_BEV = False
_C.VAD_VECTOR_QUERY_SEED_SCALE = 1.0
_C.VAD_VECTOR_RISK_GATE_ENABLED = False
_C.VAD_VECTOR_RISK_GATE_THRESH = 0.08
_C.VAD_VECTOR_RISK_GATE_TEMP = 0.04
_C.VAD_VECTOR_RISK_GATE_FLOOR = 0.0
_C.VAD_TRAJ_RESIDUAL_ENABLED = False
_C.VAD_TRAJ_RESIDUAL_SCALE = 0.5
_C.STAGE1_DETACH_BEV = False
_C.STAGE2_FREEZE_PERCEPTION = True
_C.STAGE2_TRAIN_VAD_ADAPTER_ONLY = True
_C.VAD_AGENT_QUERY_NUM = 16
_C.VAD_MAP_QUERY_NUM = 8
_C.VAD_MAP_POINTS_PER_QUERY = 8
_C.VAD_VECTOR_AGENT_CENTER_RADIUS = 3.0
_C.VAD_VECTOR_TARGET_TOPK = 16
_C.VAD_VECTOR_FUTURE_TOPK = 16
_C.VAD_VECTOR_MAP_TOPK = 32
_C.VAD_AGENT_FUTURE_DELTA_SCALE = 4.0
_C.LOSS_VAD_AGENT_W = 0.05
_C.LOSS_VAD_MAP_W = 0.02
_C.LOSS_PLAN_MAP_BOUND_W = 0.0
_C.LOSS_PLAN_MAP_DIR_W = 0.0
_C.VAD_CORRIDOR_X_MIN = 0.0
_C.VAD_CORRIDOR_X_MAX = 45.0
_C.VAD_CORRIDOR_Y_ABS = 10.0
_C.VAD_RISK_TARGET_DILATE = 3
_C.VAD_RISK_VISIBLE_DILATE = 3
_C.VAD_RISK_BOX_SAMPLE_X = 5
_C.VAD_RISK_BOX_SAMPLE_Y = 9
_C.VAD_GT_SAFE_COL_THRESH = 0.2
_C.BEV_AUX_USE_FRONT_CORRIDOR = True
_C.BEV_CORRIDOR_X_MIN = 0.0
_C.BEV_CORRIDOR_X_MAX = 45.0
_C.BEV_CORRIDOR_Y_ABS = 10.0
_C.BEV_AUX_TARGET_DILATE = 3
_C.BEV_AUX_VISIBLE_DILATE = 3
_C.GPVL_TEACHER_FEATURE_ROOT = ""
_C.GPVL_TEACHER_FEATURE_DIM = 256
_C.IPM = CN()
_C.IPM.MPP = 0.10

_C.PRETRAINED = CN()
_C.PRETRAINED.LOAD_WEIGHTS = False
_C.PRETRAINED.PATH = ''

_C.DATASET = CN()
_C.DATASET.DATAROOT = '/data/Nuscenes'
_C.DATASET.VERSION = 'trainval'
_C.DATASET.NAME = 'nuscenes'
_C.DATASET.MAP_FOLDER = '/data/Nuscenes'
_C.DATASET.IGNORE_INDEX = 255  # Ignore index when creating flow/offset labels
_C.DATASET.FILTER_INVISIBLE_VEHICLES = True  # Filter vehicles that are not visible from the cameras
_C.DATASET.SAVE_DIR = 'datas'

_C.TIME_RECEPTIVE_FIELD = 3  # how many frames of temporal context (1 for single timeframe)
_C.EGO_HISTORY_FRAMES = 3  # ego-only history length; can be longer than TIME_RECEPTIVE_FIELD
_C.N_FUTURE_FRAMES = 4  # how many time steps into the future to predict

_C.IMAGE = CN()
_C.IMAGE.FINAL_DIM = (224, 480)
_C.IMAGE.RESIZE_SCALE = 0.3
_C.IMAGE.TOP_CROP = 46
_C.IMAGE.ORIGINAL_HEIGHT = 900  # Original input RGB camera height
_C.IMAGE.ORIGINAL_WIDTH = 1600  # Original input RGB camera width
# _C.IMAGE.NAMES = ['CAM_FRONT', 'CAM_FRONT', 'CAM_FRONT_RIGHT', 'CAM_BACK_LEFT', 'CAM_BACK', 'CAM_BACK_RIGHT']
_C.IMAGE.NAMES = ['CAM_FRONT']

_C.LIFT = CN()  # image to BEV lifting
_C.LIFT.X_BOUND = [-50.0, 50.0, 0.5]  # Forward
_C.LIFT.Y_BOUND = [-50.0, 50.0, 0.5]  # Sides
_C.LIFT.Z_BOUND = [-10.0, 10.0, 20.0]  # Height
_C.LIFT.D_BOUND = [2.0, 50.0, 1.0]
_C.LIFT.GT_DEPTH = False
_C.LIFT.DISCOUNT = 0.5
_C.LIFT.DEPTH_ROOT = "/home/cyc/dataset/nuscenes/trainval/depths"

_C.EGO = CN()
_C.EGO.WIDTH = 1.85
_C.EGO.HEIGHT = 4.084

_C.MODEL = CN()

_C.MODEL.ENCODER = CN()
_C.MODEL.ENCODER.DOWNSAMPLE = 8
_C.MODEL.ENCODER.NAME = 'efficientnet-b4'
_C.MODEL.ENCODER.OUT_CHANNELS = 64
_C.MODEL.ENCODER.USE_DEPTH_DISTRIBUTION = True

_C.MODEL.TEMPORAL_MODEL = CN()
_C.MODEL.TEMPORAL_MODEL.NAME = 'temporal_block'  # type of temporal model
_C.MODEL.TEMPORAL_MODEL.START_OUT_CHANNELS = 64
_C.MODEL.TEMPORAL_MODEL.EXTRA_IN_CHANNELS = 0
_C.MODEL.TEMPORAL_MODEL.INBETWEEN_LAYERS = 0
_C.MODEL.TEMPORAL_MODEL.PYRAMID_POOLING = True
_C.MODEL.TEMPORAL_MODEL.INPUT_EGOPOSE = True

_C.MODEL.DISTRIBUTION = CN()
_C.MODEL.DISTRIBUTION.LATENT_DIM = 32
_C.MODEL.DISTRIBUTION.MIN_LOG_SIGMA = -5.0
_C.MODEL.DISTRIBUTION.MAX_LOG_SIGMA = 5.0

_C.MODEL.FUTURE_PRED = CN()
_C.MODEL.FUTURE_PRED.N_GRU_BLOCKS = 2
_C.MODEL.FUTURE_PRED.N_RES_LAYERS = 1
_C.MODEL.FUTURE_PRED.MIXTURE = True

_C.MODEL.DECODER = CN()

_C.MODEL.BN_MOMENTUM = 0.1

_C.SEMANTIC_SEG = CN()

_C.SEMANTIC_SEG.VEHICLE = CN()
_C.SEMANTIC_SEG.VEHICLE.WEIGHTS = [1.0, 2.0]
_C.SEMANTIC_SEG.VEHICLE.USE_TOP_K = True  # backprop only top-k hardest pixels
_C.SEMANTIC_SEG.VEHICLE.TOP_K_RATIO = 0.25

_C.SEMANTIC_SEG.PEDESTRIAN = CN()
_C.SEMANTIC_SEG.PEDESTRIAN.ENABLED = True
_C.SEMANTIC_SEG.PEDESTRIAN.WEIGHTS = [1.0, 10.0]
_C.SEMANTIC_SEG.PEDESTRIAN.USE_TOP_K = True
_C.SEMANTIC_SEG.PEDESTRIAN.TOP_K_RATIO = 0.25

_C.SEMANTIC_SEG.HDMAP = CN()
_C.SEMANTIC_SEG.HDMAP.ENABLED = False
_C.SEMANTIC_SEG.HDMAP.ELEMENTS = ['lane_divider', 'drivable_area']
_C.SEMANTIC_SEG.HDMAP.WEIGHTS = [[1.0, 5.0], [1.0, 1.0]]
_C.SEMANTIC_SEG.HDMAP.TRAIN_WEIGHT = [1, 1]
_C.SEMANTIC_SEG.HDMAP.USE_TOP_K = [True, False]
_C.SEMANTIC_SEG.HDMAP.TOP_K_RATIO = [0.25, 0.25]

_C.INSTANCE_SEG = CN()
_C.INSTANCE_SEG.ENABLED = True

_C.INSTANCE_FLOW = CN()
_C.INSTANCE_FLOW.ENABLED = True

_C.PROBABILISTIC = CN()
_C.PROBABILISTIC.ENABLED = True  # learn a distribution over futures
_C.PROBABILISTIC.METHOD = 'GAUSSIAN' # [BERNOULLI, GAUSSIAN, MIXGAUSSIAN]

_C.PLANNING = CN()
_C.PLANNING.ENABLED = True
_C.PLANNING.GRU_STATE_SIZE = 256
_C.PLANNING.SAMPLE_NUM = 600
_C.PLANNING.COMMAND = ['LEFT', 'FORWARD', 'RIGHT']

_C.LOSS_BOX_COL_W = 10.0
_C.LOSS_BOX_COL_AR_ALPHA = 1.0
_C.BOX_RISK_REDUCE = 'topk'
_C.BOX_RISK_POW = 2.0
_C.BOX_RISK_TOPK_FRAC = 0.34

_C.LOSS_PED_REPULSE_W = 1.5
_C.LOSS_PED_REPULSE_AR_ALPHA = 1.0
_C.LOSS_PED_REPULSE_SAFE_DIST = 6.0
_C.PED_REPULSE_WARMUP_STEPS = 0
_C.PED_REPULSE_RAMP_STEPS = 1000
_C.PED_GATE_MIN = 0.15
_C.PED_GATE_INIT_BIAS = 0.0
_C.PED_START_STEP = 2
_C.PED_RAMP_STEEPNESS = 1.5
_C.PED_CTX_SCALE = 0.35
_C.PED_BEV_SCALE = 0.8
_C.PED_BEV_GATE_MIN = 0.08
_C.PED_RISK_GATE_SAFE_DIST = 5.0
_C.PED_RISK_ADAPTER_HIDDEN_DIM = 128
_C.PED_RISK_ADAPTER_MAX_DELTA = 1.0
_C.PED_FINETUNE_TARGET_RATIO = 0.5
_C.PED_FINETUNE_TRIGGERED_RATIO = 0.3
_C.PED_FINETUNE_HAS_PED_RATIO = 0.3
_C.PED_FINETUNE_NORMAL_RATIO = 0.4
_C.PED_FINETUNE_SAMPLING = 'three_way'
_C.PED_FINETUNE_SAFE_DIST = 6.0
_C.PED_FINETUNE_TRAINABLE_MODE = 'ped_only'

_C.FUTURE_DISCOUNT = 0.95

_C.OPTIMIZER = CN()
_C.OPTIMIZER.LR = 3e-4
_C.OPTIMIZER.CLIP_LR = 3e-5
_C.OPTIMIZER.FIXED_LR = False
_C.OPTIMIZER.WEIGHT_DECAY = 1e-7
_C.GRAD_NORM_CLIP = 5

_C.COST_FUNCTION = CN()
_C.COST_FUNCTION.SAFETY = 0.1
_C.COST_FUNCTION.LAMBDA = 1.
_C.COST_FUNCTION.HEADWAY = 1.
_C.COST_FUNCTION.LRDIVIDER = 10. 
_C.COST_FUNCTION.COMFORT = 0.1
_C.COST_FUNCTION.PROGRESS = 0.5
_C.COST_FUNCTION.VOLUME = 100.

def get_parser():
    parser = argparse.ArgumentParser(description='Fiery training')
    parser.add_argument('--config-file', default='', metavar='FILE', help='path to config file')
    parser.add_argument(
        'opts', help='Modify config options using the command-line', default=None, nargs=argparse.REMAINDER,
    )
    return parser


def get_cfg(args=None, cfg_dict=None):
    """ First get default config. Then merge cfg_dict. Then merge according to args. """

    cfg = _C.clone()

    if cfg_dict is not None:
        tmp = CfgNode(cfg_dict)
        for i in tmp.COST_FUNCTION:
            tmp.COST_FUNCTION.update({i: float(tmp.COST_FUNCTION.get(i))})
        cfg.merge_from_other_cfg(tmp)

    if args is not None:
        if args.config_file:
            cfg.merge_from_file(args.config_file)
        cfg.merge_from_list(args.opts)
        # cfg.freeze()
    return cfg
